// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	// Anthropicの環境変数
	ANTHROPIC_API_KEY: string;
	ANTHROPIC_MODEL: string;
	NODE_VERSION: string;
}
